= Robert's Rules of Poker for Home Games
Robert Ciaffone
v11
:toc: left
:sectnums:
:xrefstyle: full

“Robert’s Rules Of Poker” is authored by Robert Ciaffone, better known in the poker world as Bob Ciaffone, a leading authority on cardroom rules.
He is the person who has selected which rules to use, and formatted, organized, and worded the text.
Nearly all these rules are substantively in common use for poker, but many improved ideas for wording and organization are employed throughout this work.
A lot of the rules are similar to those used in the rulebook of cardrooms where he has acted as a rules consultant and rules drafter.
Ciaffone authored the rulebook for the Poker Players Association (founded in 1984, now defunct), the first comprehensive set of poker rules for the general public.
He has done extensive work on rules for the Las Vegas Hilton, The Mirage, and Hollywood Park Casino, and assisted many other cardrooms.
Ciaffone is a regular columnist for Card Player magazine, and can be reached through that publication. This rulebook will be periodically revised, so suggestions are welcome.

WARNING: Anyone contemplating the hosting of a private game should make sure what he is doing is not in violation of the law.
Most laws governing private poker games are made at the state level.
No state in our country allows a person to run a poker game as a business.
Raking pots and charging an hourly rate for playing are two examples of activities only a licensed commercial cardroom would be allowed to do.
Some states prohibit the playing of poker for money, because they prohibit any kind of gambling.
Other states allow social gambling.
Even though gambling laws may sometimes enforced only sporadically, they do exist, and people are prosecuted for violating them.
Check out the penal code in your state and protect yourself, your family, and your friends by obeying the law.
This rulebook is not to be construed in any way as an aid to breaking the law.
It’s purpose is simply to maintain order by providing a fair framework for playing poker in a situation where the game is legal.

This rulebook for private games was made by taking the document constructed for cardroom use and making the appropriate changes.
Most of those changes are in wording, but there are a few of substance.
Here are some examples.
A warning is given regarding the legality of hosting a poker game.
The restriction on the maximum number of raises on a betting round was set at a bet and three raises for all limit poker forms, which is the traditional rule for private games.
The procedure for shuffling and cutting is described. The time one may be gone from a game has been shortened.

This rulebook is copyright protected.
It may not be used for any commercial purpose without the specific consent of Robert Ciaffone, its author.

== Proper Behavior

=== Conduct Code

We will attempt to maintain a pleasant environment for all our players, but are not responsible for the conduct of any player.
We have established a code of conduct, and may deny the privilege to play in our game to anyone who violates it.
The following is not permitted:

* Collusion with another player or any other form of cheating.
* Verbally or physically threatening anyone.
* Using profanity or obscene language.
* Creating a disturbance by arguing, shouting, or making excessive noise.
* Throwing, tearing, bending, or crumpling cards.
* Destroying or defacing property.
* Using an illegal substance.
* Carrying a weapon.

=== Poker Etiquette

The following actions are improper, and grounds for warning, suspending, or barring a violator:

* Deliberately acting out of turn.
* Deliberately splashing chips into the pot.
* Agreeing to check a hand out when a third player is all-in.
* Reading a hand for another player at the showdown before it has been placed faceup on the table.
* Telling anyone to turn a hand faceup at the showdown.
* Revealing the contents of a live hand in a multihanded pot before the betting is complete.
* Needlessly stalling the action of a game.
* Deliberately discarding hands away from the muck. Cards should be released in a low line of flight, at a moderate rate of speed.
* Stacking chips in a manner that interferes with dealing or viewing cards.
* Making statements or taking action that could unfairly influence the course of play, whether or not the offender is involved in the pot.

== House Policies

=== Decision-Making

. Taking a seat in a poker game means you agree to abide by the rules for that game and the decision-making process used in it.
. The proper time to draw attention to an error or irregularity is when it occurs or is first noticed.
	Any delay may affect the ruling.
. If an incorrect rule interpretation or decision is made in good faith, there shall be no liability incurred by the decision-maker.
. A ruling may be made regarding a pot if it has been requested before the next deal starts (or before the game either ends or changes to another table).
	Otherwise, the result of a deal must stand.
	The first riffle of the shuffle marks the start for a deal.
. If a pot has been incorrectly awarded and mingled with chips that were not in the pot, but the time limit for a ruling request given in the previous rule has been complied with, the betting may be reconstructed, and the proper amount transferred to the respective players.
. To keep the action moving, it is possible that a game may continue even though a decision is delayed for a short period.
	In such circumstances, a pot or portion thereof may be impounded while the decision is pending.
. The same action may have a different meaning, depending on who does it, so the possible intent of an offender will be taken into consideration.
	Some factors here are the person’s amount of poker experience and past record.

=== Procedures

. The poker form and stakes that had been agreed upon when the game was started shall not be changed if more than one player objects.
. Cash is not permitted on the table. All cash should be changed into chips in order to play.
. The establishment is not responsible for any shortage or removal of chips left on the table during a player’s absence, even though everyone should try to protect the game as best they can.
. All games are table stakes.
	Only the chips in front of a player at the start of a deal may play for that hand, except for chips not yet received that a player has purchased.
	The amount bought must be announced to the table, or only the amount of the minimum buy-in plays. 
. If you return to the game within one hour of cashing out, your buy-in must be equal to the amount removed when leaving that game.
. All chips must be kept in plain view.
. Playing out of a chip rack is not allowed.
. Only one person may play a hand.
. No one is allowed to play another player’s chips.
. Playing over may be allowed if that is customary, but only with permission from the absent player (unless he has left the premises for some length of time) and protection for that person’s chips.
. Pushing bets (“saving” or “potting out”) is not allowed.
. Pushing an ante or posting for another person is not allowed.
. Splitting pots by agreement will not be allowed.
	Chopping the big and small blind by taking them back when all other players have folded may be allowed in non-tournament button games, if that is customary.
. Insurance propositions are not allowed.
	Dealing twice (or three times) when all-in is permitted at big-bet poker.
. Players must keep their cards in full view.
	This means above table-level and not past the edge of the table.
	The cards should not be covered by the hands in a manner to completely conceal them.
. Any player is entitled to a clear view of an opponent’s chips.
	Higher denomination chips should be easily visible.
. Your chips may be picked up if you are away from the table for more than 15 minutes, unless you have made a specific arrangement to leave for a longer length of time.
	Frequent absences may cause your chips to be removed from the table.
. A new deck must be used for at least a full round (once around the table) before it may be changed, unless a deck is defective or damaged, or cards become sticky.
. Looking through the discards or deck stub is not allowed.
. A player is expected to pay attention to the game and not hold up play.
	Activity that interferes with this such as reading at the table is discouraged, and the player will be asked to cease if a problem is caused.
. A non-player may not sit at the table.
. You may have a guest sit behind you only if no one in the game objects.
	It is improper for a guest to look at any hand other then your own.
. Speaking in a foreign language during a deal is not allowed.

=== Seating

. When a button game starts, active players will draw a card for the button position.
	The button will be awarded to the highest card by suit.
. In starting a game, the player who arrives the earliest gets first choice of remaining seats.
	A certain seat may be reserved for a player for good reason.
	Example: to assist in ease of reading the board for a person with a vision problem.
. A player who is already in the game has precedence over a new player for any seat when it becomes available.
	However, no change will occur after a new player has been seated and received chips.
	For players already in the game, the one who asks the earliest has preference for a seat change.

== General Poker Rules

=== The Buy-in

. When you enter a game, you must make a full buy-in for that particular game.
	A full buy-in at limit poker is at least ten times the maximum bet for the game being played, unless designated otherwise.
	A full buy-in at pot-limit or no-limit poker is forty times the minimum bring-in (usually, the size of the big blind), unless designated otherwise.
. Only one short buy-in is allowed per session.
. Adding to your stack is not considered a buy-in, and may be done in any quantity between hands.

=== The Shuffle and Cut

. The pack must be shuffled and cut before the cards are dealt.
	The recommended method to protect the integrity of the game is to have three people involved instead of only two.
	The dealer on the previous hand takes in the discards and squares up the deck prior to the shuffle.
	The player on the new dealer’s left shuffles the cards and then slides the pack to the new dealer, who gets them cut by the player on his right.
. The deck must be riffled a minimum of four times. The cut must leave a minimum of four cards in each portion.
. The bottom of the deck should be protected so nobody can see the bottom card.
	This is done by using a cut-card. A joker may be used as a cut-card.
. Any complaint about the shuffle, cut, or other preparation connected with dealing must be made before the player has looked at his hand or betting action has started.

=== Misdeals

. The following circumstances cause a misdeal, provided attention is called to the error before two players have acted on their hands.
	(If two players have acted in turn, the deal must be played to conclusion, as explained in rule #2)
.. The first or second card of the hand has been dealt faceup or exposed through dealer error.
.. Two or more cards have been exposed by the dealer.
.. Two or more boxed cards (improperly faced cards) are found.
.. Two or more extra cards have been dealt in the starting hands of a game.
.. An incorrect number of cards has been dealt to a player, except the top card may be dealt if it goes to the player in proper sequence.
.. Any card has been dealt out of the proper sequence (except an exposed card may be replaced by the burncard).
.. The button was out of position.
.. The first card was dealt to the wrong position.
.. Cards have been dealt to an empty seat or a player not entitled to a hand.
.. A player has been dealt out who is entitled to a hand.
	This player must be present at the table or have posted a blind or ante.
. Action is considered to occur in stud games when two players after the forced bet have acted on their hands.
	In button games, action is considered to occur when two players after the blinds have acted on their hands.
	Once action occurs, a misdeal can no longer be declared.
	The hand will be played to conclusion and no money will be returned to any player whose hand is fouled.

=== Dead Hands

. Your hand is declared dead if:
.. You fold or announce that you are folding when facing a bet or a raise.
.. You throw your hand away in a forward motion causing another player to act behind you (even if notfacing a bet).
.. In stud, when facing a bet, you pick your upcards off the table, turn your upcards facedown, or mix yourupcards and downcards together.
.. The hand does not contain the proper number of cards for that poker form (except at stud a hand missingthe final card may be ruled live, and at lowball and draw high a hand with too few cards before the draw islive). [See Section 16 - “Explanations,” discussion #4, for more information on the stud portion of thisrule.]
.. You act on a hand with a joker as a holecard in a game not using a joker. (A player who acts on a handwithout looking at a card assumes the liability of finding an improper card, as given in Irregularities, rule#8.)
.. You have the clock on you when facing a bet or raise and exceed the specified time limit.
. Cards thrown into the muck may be ruled dead. However, a hand that is clearly identifiable may be retrieved ifdoing so is in the best interest of the game. An extra effort should be made to rule a hand retrievable if it wasfolded as a result offalse information given to the player.
. Cards thrown into another player’s hand are dead, whether they are faceup or facedown.

=== Irregularities

. In button games, if it is discovered that the button was placed incorrectly on the previous hand, the button andblinds will be corrected for the new hand in a manner that gives every player one chance for each position onthe round (if possible).
. You must protect your own hand at all times. Your cards may be protected with your hands, a chip, or otherobject placed on top of them. If you fail to protect your hand, you will have no redress if it becomes fouled orthe dealer accidentally kills it.
. If a card with a different color back appears during a hand, all action is void and all chips in the pot arereturned to the respective bettors. If a card with a different color back is discovered in the stub, all actionstands.
. If two cards of the same rank and suit are found, all action is void, and all chips in the pot are returned to theplayers who wagered them (subject to next rule).
. A player who knows the deck is defective has an obligation to point this out. If such a player instead tries towin a pot by taking aggressive action (trying for a freeroll), the player may lose the right to a refund, and thechips may be required to stay in the pot for the next deal.
. If there is extra money in the pot on a deal as a result of forfeited money from the previous deal (as per rule#5), or some similar reason, only a player dealt in on the previous deal is entitled to a hand.
. A card discovered faceup in the deck (boxed card) will be treated as a meaningless scrap of paper. A cardbeing treated as a scrap of paper will be replaced by the next card below it in the deck, except when the nextcard has already been dealt facedown to another player and mixed in with other downcards. In that case, thecard that was faceup in the deck will be replaced after all other cards are dealt for that round.
. A joker that appears in a game where it is not used is treated as a scrap of paper. Discovery of a joker does notcause a misdeal. If the joker is discovered before a player acts on his or her hand, it is replaced as in theprevious rule. If the player does not call attention to the joker before acting, then the player has a dead hand.
. If you play a hand without looking at all of your cards, you assume the liability of having an irregular card oran improper joker.
. One or more cards missing from the deck does not invalidate the results of a hand.
. Before the first round of betting, if a dealer deals one additional card, it is returned to the deck and used as theburncard.
. Procedure for an exposed card varies with the poker form, and is given in the section for each game. A cardthat is flashed by a dealer is treated as an exposed card. A card that is flashed by a player will play. To obtain aruling on whether a card was exposed and should be replaced, a player should announce that the card wasflashed or exposed before looking at it. A downcard dealt off the table is an exposed card.
. If a card is exposed due to dealer error, a player does not have an option to take or reject the card. The situationwill be governed by the rules for the particular game being played.
. If you drop any cards out of your hand onto the floor, you must still play them.
. If the dealer prematurely deals any cards before the betting is complete, those cards will not play, even if aplayer who has not acted decides to fold.

=== Betting and Raising

. Check-raise is permitted in all games, except in certain forms of lowball.
. In no-limit and pot-limit games, unlimited raising is allowed.
. In limit poker, for a pot involving three or more players who are not all-in, there is a maximum of a bet andthree raises allowed.
. Unlimited raising for money games is allowed in heads-up play. This applies any time the action becomesheads-up before the raising has been capped. Once the raising is capped on a betting round, it cannot beuncapped by a subsequent fold that leaves two players heads-up. For tournament play, the three raise maximumfor limit poker applies when heads-up as well.
. In limit play, an all-in wager of less than half a bet does not reopen the betting for any player who has alreadyacted and is in the pot for all previous bets. A player facing less than half a bet may fold, call, or complete thewager. An all-in wager of a half a bet or more is treated as a full bet, and a player may fold, call, or make a fullraise. (An example of a full raise is on a $20 betting round, raising a $15 all-in bet to $35).
. Any wager must be at least the size of the previous bet or raise in that round, unless a player is going all-in.
. The smallest chip that may be wagered in a game is the smallest chip used in the antes and/or blinds. Smallerchips than this do not play even in quantity, so a player wanting action on such chips must change them upbetween deals. If betting is in dollar units or greater, a fraction of a dollar does not play. A player going all-inmust put all chips that play into the pot.
. A verbal statement denotes your action and is binding. If in turn you verbally declare a fold, check, bet, call, orraise, you are forced to take that action.
. Rapping the table with your hand is a pass.
. Deliberately acting out of turn will not be tolerated. A player who checks out of turn may not bet or raise onthe next turn to act. An action or verbal declaration out of turn may be ruled binding if there is no bet, call, orraise by an intervening player acting after the infraction has been committed.
. To retain the right to act, a player must stop the action by calling “time” (or an equivalent word). Failure tostop the action before three or more players have acted behind you may cause you to lose the right to act. You cannot forfeit your right to act if any player in front of you has not acted, only if you fail to act when it legallybecomes your turn. Therefore, if you wait for someone whose turn comes before you, and three or moreplayers act behind you, this still does not hinder your right to act.
. A player who bets or calls by releasing chips into the pot is bound by that action. However, if you are unawarethat the pot has been raised, you may withdraw that money and reconsider your action, provided that no oneelse has acted after you.
. In limit poker, if you make a forward motion into the pot area with chips and thus cause another player to act,you may be forced to complete your action.
. String raises are not allowed. To protect your right to raise, you should either declare your intention verbally orplace the proper amount of chips into the pot. Putting a full bet plus a half-bet or more into the pot isconsidered to be the same as announcing a raise, and the raise must be completed.(This does not apply in theuse of a single chip of greater value.)
. If you put a single chip in the pot that is larger than the bet, but do not announce a raise, you are assumed tohave only called. Example: In a $3-$6 game, when a player bets $6 and the next player puts a $25 chip in thepot without saying anything, that player has merely called the $6 bet.
. All wagers and calls of an improperly low amount must be brought up to proper size if the error is discoveredbefore the betting round has been completed. This includes actions such as betting a lower amount than theminimum bring-in (other than going all-in) and betting the lower limit on an upper limit betting round. If awager is supposed to be made in a rounded off amount, is not, and must be corrected, it shall be changed to theproper amount nearest in size. No one who has acted may change a call to a raise because the wager size hasbeen changed.

=== The Showdown


. A player must show all cards in the hand face-up on the table to win any part of the pot.
. Cards speak (cards read for themselves). The dealer assists in reading hands, but players are responsible forholding onto their cards until the winner is declared. Although verbal declarations as to the contents of a handare not binding, deliberately miscalling a hand with the intent of causing another player to discard a winninghand is unethical and may result in forfeiture of the pot. (For more information on miscalling a hand see“Section 11 - Lowball,” Rule 15 and Rule 16.)
. Anyone who sees an incorrect amount of chips put into the pot, or an error about to be made in awarding a pot,has an ethical obligation to point out the error. Please help us keep mistakes of this nature to a minimum.
. All losing hands will be killed by the dealer before a pot is awarded.
. Any player who has been dealt in may request to see any hand that has been called, even if the opponent's handor the winning hand has been mucked. However, this is a privilege that may be revoked if abused. If a player other than the pot winner asks to see a hand that has been folded, that hand is dead. If the winning player asksto see a losing player’s hand, both hands are live, and the best hand wins.
. If you show cards to another player during or after a deal, any player at the table has the right to see thoseexposed cards. Cards shown during a deal to a player not in the pot should only be shown to all players whenthe deal is finished.
. If everyone checks (or is all-in) on the final betting round, the player who acted first is the first to show thehand. If there is wagering on the final betting round, the last player to take aggressive action by a bet or raiseis the first to show the hand. In order to speed up the game, a player holding a probable winner is encouragedto show the hand without delay. If there is a side pot, players involved in the side pot should show their handsbefore anyone who is all-in for only the main pot.

=== Ties

. The ranking of suits from highest to lowest is spades, hearts, diamonds, clubs. Suits never break a tie forwinning a pot. Suits are used to break a tie between cards of the same rank (no redeal or redraw).
. Dealing a card to each player is used to determine things like who moves to another table. If the cards aredealt, the order is clockwise starting with the first player on the dealer’s left (the button position is irrelevant).Drawing a card is used to determine things like who gets the button in a new game.
. An odd chip will be broken down to the smallest unit used in the game.
. No player may receive more than one odd chip.
. If two or more hands tie, an odd chip will be awarded as follows:
.. In a button game, the first hand clockwise from the button gets the odd chip.
.. In a stud game, the odd chip will be given to the highest card by suit in all high games, and to the lowestcard by suit in all low games. (When making this determination, all cards are used, not just the five cardsthat constitute the player's hand.)
.. In high-low split games, the high hand receives the odd chip in a split between the high and the low hands.The odd chip between tied high hands is awarded as in a high game of that poker form, and the odd chipbetween tied low hands is awarded as in a low game of that poker form.
.. All side pots and the main pot will be split as separate pots, not mixed together.

== Button and Blind Use

In button games, If the players deal the cards themselves, “the button” refers to the person who dealt the cards. (Ifa non-playing dealer does the actual dealing, a round disk called the button is used to indicate which player has the dealer position.) The player with the button is last to receive cards on the initial deal and has the right of lastaction after the first betting round. The button moves clockwise after a deal ends to rotate the advantage of lastaction. One or more blind bets are usually used to stimulate action and initiate play. Blinds are posted before theplayers look at their cards. Blinds are part of a player’s bet, unless the structure of a game or the situation requirespart or all of a particular blind to be “dead.” Dead chips are not part of a player’s bet. With two blinds, the smallblind is posted by the player immediately clockwise from the button, and the big blind is posted by the player twopositions clockwise from the button. With more than two blinds, the little blind is normally left of the button (noton it). Action is initiated on the first betting round by the first player to the left of the blinds. On all subsequent betting rounds, the action begins with the first active player to the left of the button.

.Rules for Using Blinds
. Each round every player must get an opportunity for the button, and meet the total amount of the blindobligations. Either of the following methods of button and blind placement may be designated to do this:
.. Moving button – The button always moves forward to the next player and the blinds adjust accordingly.There may be more than one big blind.
.. Dead button – The big blind is posted by the player due for it, and the small blind and button arepositioned accordingly, even if this means the small blind or the button is placed in front of an empty seat,giving the same player the privilege of last action on consecutive hands.[See “Section 16 – Explanations,” discussion #1, for more information on this rule.]
. A player who posts a blind has the option of raising the pot at the first turn to act. (This does not apply when a"dead blind" for the collection is used in a game and has been posted).
. In heads-up play with two blinds, the small blind is on the button.
. A new player entering the game has the following options:
.. Wait for the big blind.
.. Post an amount equal to the big blind and immediately be dealt a hand. (In lowball, a new player musteither post an amount double the big blind or wait for the big blind.)
. A new player who elects to let the button go by once without posting is not treated as a player in the game whohas missed a blind, and needs to post only the big blind when entering the game.
. A person playing over is considered a new player, and must post the amount of the big blind or wait for the bigblind.
. A new player cannot be dealt in between the big blind and the button. Blinds may not be made up between thebig blind and the button. You must wait until the button passes. [See “Section 16 – Explanations,” discussion#3, for more information on this rule.]
. When you post the big blind, it serves as your opening bet. When it is your next turn to act, you have theoption to raise.
. A player who misses any or all blinds can resume play by either posting all the blinds missed or waiting for thebig blind. If you choose to post the total amount of the blinds, an amount up to the size of the minimumopening bet is live. The remainder is taken by the dealer to the center of the pot and is not part of your bet.When it is your next turn to act, you have the option to raise.
. If a player who owes a blind (as a result of a missed blind) is dealt in without posting, the hand is dead if theplayer looks at it before putting up the required chips, and has not yet acted. If the player acts on the hand andplays it, putting chips into the pot before the error is discovered, the hand is live, and the player is required topost on the next deal.
. A player who goes all-in and loses is obligated to make up the blinds if they are missed before a rebuy is made.(The person is not treated as a new player when reentering.)
. These rules about blinds apply to a newly started game:
.. Any player who drew for the button is considered active in the game and is required to make up anymissed blinds.
.. A new player will not be required to post a blind until the button has made one complete revolution aroundthe table, provided a blind has not yet passed that seat.
.. A player may change seats without penalty, provided a blind has not yet passed the new seat.
. In all multiple-blind games, a player who changes seats will be dealt in on the first available hand in the samerelative position. Example: If you move two active positions away from the big blind, you must wait twohands before being dealt in again. If you move closer to the big blind, you can be dealt in without any penalty.If you do not wish to wait and have not yet missed a blind, then you can post an amount equal to the big blindand receive a hand. (Exception: At lowball you must kill the pot, wait for the same relative position, or waitfor the big blind; see “Section 11 – Lowball,” rule #7.)
. A player who "deals off" (by playing the button and then immediately getting up to change seats) can allow theblinds to pass the new seat one time and reenter the game behind the button without having to post a blind.
. A live “straddle bet" is not allowed at limit poker except in specified games.

[#holdem]
== Hold'em

In hold’em, players receive two downcards as their personal hand (holecards), after which there is a round ofbetting. Three boardcards are turned simultaneously (called the “flop”) and another round of betting occurs. Thenext  two  boardcards are  turned one  at  a  time,  with  a  round  of  betting after  each  card.  The  boardcards arecommunity cards, and a player may use any five-card combination from among the board and personal cards. Aplayer may even use all of the boardcards and no personal cards to form a hand (play the board). A dealer button is used. The usual structure is to use two blinds, but it is possible to play the game with one blind, multiple blinds,an ante, or combination of blinds plus an ante.

These rules deal only with irregularities. See the previous chapter, <<Button and Blind Use>>, for rules on that subject.

.Rules
. If the first holecard dealt is exposed, a misdeal results. The dealer will retrieve the card, reshuffle, and recut thecards. If any other holecard is exposed due to a dealer error, the deal continues. The exposed card may not bekept. After completing the hand, the dealer replaces the card with the top card on the deck, and the exposedcard is then used for the burncard. If more than one holecard is exposed, this is a misdeal and there must be aredeal.
. If the flop contains too many cards, it must be redealt. (This applies even if it were possible to know whichcard was the extra one.)
. If the flop needs to be redealt because the cards were prematurely flopped before the betting was complete, orthe flop contained too many cards, the boardcards are mixed with the remainder of the deck. The burncardremains on the table. After shuffling, the dealer cuts the deck and deals a new flop without burning a card.[See “Section 16 – Explanations,” discussion #2, for more information on this rule.]
. If the dealer turns the fourth card on the board before the betting round is complete, the card is taken out ofplay for that round, even if subsequent players elect to fold. The betting is then completed. The dealer burnsand turns what would have been the fifth card in the fourth card’s place. After this round of betting, the dealerreshuffles the deck, including the card that was taken out of play, but not including the burncards or discards.The dealer then cuts the deck and turns the final card without burning a card. If the fifth card is turned upprematurely, the deck is reshuffled and dealt in the same manner. [See “Section 16 – Explanations,” discussion#2, for more information on this rule.]
. If the dealer mistakenly deals the first player an extra card (after all players have received their starting hands),the card will be returned to the deck and used for the burncard. If the dealer mistakenly deals more than oneextra card, it is a misdeal.
. You must declare that you are playing the board before you throw your cards away; otherwise you relinquishall claim to the pot.

== Omaha

Omaha is similar to hold’em in using a three-card flop on the board, a fourth boardcard, and then a fifth boardcard.Each player is dealt four holecards (instead of two) at the start. In order to make a hand, a player must use preciselytwo holecards with three boardcards. The betting is the same as in hold'em. At the showdown, the entire four-cardhand should be shown to receive the pot.

.Rules of Omaha
. All the rules of hold’em apply to Omaha except the rule on playing the board, which is not possible in Omaha(because you must use two cards from your hand and three cards from the board).

== Omaha High-Low

Omaha is often played high-low split, 8-or-better. The player may use any combination of two holecards and threeboardcards for the high hand and another (or the same) combination of two holecards and three boardcards for thelow hand.The rules governing kill pots are listed in “Section 13 – Kill Pots.”

.Rules of Omaha High-Low
. All the rules of Omaha apply to Omaha high-low splitexcept as below.
. A qualifier of 8-or-better for low applies to all high-low split games, unless a specific posting to the contrary isdisplayed. If there is no qualifying hand for low, the best high hand wins the whole pot.

== Seven-Card Stud

Seven-card stud is played with two downcards and one upcard dealt before the first betting round, followed bythree more upcards (with a betting round after each card). After the last downcard is dealt, there is a final round ofbetting. The best five-card poker hand wins the pot. In all fixed-limit games, the smaller bet is wagered on the firsttwo betting rounds, and the larger bet is wagered after the betting rounds on the fifth, sixth, and seventh cards. Ifthere is an open pair on the fourth card, any player has the option of making the smaller or larger bet. Deliberatelychanging the order of your upcards in a stud game is improper because it unfairly misleads the other players.

.Rules of Seven-Card Stud
. The first round of betting starts with a forced bet by the lowest upcard by suit. On subsequent betting rounds,the high hand on board initiates the action (a tie is broken by position, with the player who received cards firstacting first).
. The player with the forced bet has the option of opening for a full bet.
. Increasing the amount wagered by the opening forced bet up to a full bet does not count as a raise, but merelyas a completion of the bet. For example: In $15-$30 stud, the lowcard opens for $5. If the next playerincreases the bet to $15 (completes the bet), up to three raises are then allowed when using a three-raise limit.
. In all fixed-limit games, when an open pair is showing on fourth street (second upcard), any player has theoption of betting either the lower or the upper limit. For example: In a $5-$10 game, if you have a pairshowing and are the high hand, you may bet either $5 or $10. If you bet $5, any player then has the option to call $5, raise $5, or raise $10. If a $10 raise is made, then all other raises must be in increments of $10. If theplayer high with the open pair on fourth street checks, then subsequent players have the same options thatwere given to the player who was high.
. If your first or second holecard is accidentally turned up by the dealer, then your third card will be dealt down.If both holecards are dealt up, you have a dead hand and receive your ante back. If the first card dealt faceupwould have been the lowcard, action starts with the first hand to that player’s left. That player may fold, openfor the forced bet, or open for a full bet. (In tournament play, if a downcard is dealt faceup, a misdeal iscalled.)
. If you are not present at the table when it is your turn to act on your hand, you forfeit your ante and yourforced bet, if any. If you have not returned to the table in time to act, the hand will be killed when the bettingreaches your seat.
. If a hand is folded when there is no wager, that seat will continue to receive cards until the hand is killed as aresult of a bet.
. If you are all in for the ante and have the lowcard, the player to your left acts first. That player may fold, openfor the forced bet, or open for a full bet.
. If the wrong person is designated as low and that person bets, the action will be corrected to the true lowcard ifthe next player has not yet acted. The incorrect lowcard takes back the wager and the true lowcard must bet. Ifthe next hand has acted after the incorrect lowcard wager, the wager stands, action continues from there, andthe true lowcard has no obligations.
. If you pick up your upcards without calling when facing a wager, this is a fold and your hand is dead. This acthas no significance at the showdown because betting is over; the hand is live until discarded.
. A card dealt off the table must play and it is treated as an exposed card.
. Dealers should not announce possible straights or flushes.
. If the dealer burns two cards for one round or fails to burn a card, the cards will be corrected, if at all possible,to their proper positions. If this should happen on a final downcard, and either a card intermingles with aplayer's other holecards or a player looks at the card, the player must accept that card.
. If the dealer burns and deals one or more cards before a round of betting has been completed, the card(s) mustbe eliminated from play. After the betting for that round is completed, an additional card for each remainingplayer still active in the hand is also eliminated from play (to later deal the same cards to the players whowould have received them without the error). After that round of betting has concluded, the dealer burns a cardand play resumes. The removed cards are held off to the side in the event the dealer runs out of cards. If theprematurely dealt card is the final downcard and has been looked at or intermingled with the player's otherholecards, the player must keep the card, and on sixth street betting may not bet or raise (because the playernow has all seven cards). 
. If there are not enough cards left in the deck for all players, all the cards are dealt except the last card, which ismixed with the burncards (and any cards removed from the deck, as in the previous rule). The dealer thenscrambles and cuts these cards, burns again, and delivers the remaining downcards, using the last card ifnecessary. If there are not as many cards as players remaining without a card, the dealer does not burn, so thateach player can receive a fresh card. If the dealer determines that there will not be enough fresh cards for all ofthe remaining players, then the dealer announces to the table that a common card will be used. The dealer willburn a card and turn one card faceup in the center of the table as a common card that plays in everyone’s hand.The player who is now high using the common card initiates the action for the last round.
. An all-in player should receive holecards dealt facedown, but if the final holecard to such a player is dealtfaceup, the card must be kept, and the other players receive their normal card.
. If the dealer turns the last card faceup to any player, the hand now high on the board using all the upcards willstart the action. The following rules apply to the dealing of cards:
.. If there are more than two players, all remaining players receive their last card facedown. A player whoselast card is faceup has the option of declaring all-in (before betting action starts).
.. If there are only two players remaining and the first player's final downcard is dealt faceup, the secondplayer's final downcard will also be dealt faceup, and the betting proceeds as normal. In the event the firstplayer's final card is dealt facedown and the opponent's final card is dealt faceup, the player with thefaceup final card has the option of declaring all-in (before betting action starts).
. A hand with more than seven cards is dead. A hand with less than seven cards at the showdown is dead, exceptany player missing a seventh card may have the hand ruled live. [See “Section 16 – Explanations,” discussion#4, for more information on this rule.]
. A player who calls a bet even though beaten by an opponent’s upcards is not entitled to a refund. (The player isreceiving information about an opponent’s hand that is not available for free.)

== Razz (Seven-Card Stud Low)

The lowest hand wins the pot. The format is similar to seven-card stud high, except the high card (aces are low) isrequired to make the forced bet on the first round, and the low hand acts first on all subsequent rounds.Straightsand flushes have no ranking, so the best possible hand is 5-4-3-2-A (a wheel). An open pair does not affect thebetting limit.

.Rules of Razz
. All seven-card stud rules apply in razz except as otherwise noted.
. The lowest hand wins the pot. Aces are low, and straights and flushes have no effect on the low value of ahand. The best possible hand is 5-4-3-2-A.
. The highest card by suit starts the action with a forced bet. The low hand acts first on all subsequent rounds. Ifthe low hand is tied, the first player clockwise from the dealer starts the action.
. Fixed-limit games use the lower limit on third and fourth streets and the upper limit on subsequent streets. Anopen pair does not affect the limit.

== Seven-Card Stud High-Low

Seven-card stud high-low split is a stud game which is played both high and low. A qualifier of 8-or-better for lowapplies to all high-low split games, unless a specific posting to the contrary is displayed. The low card initiates theaction on the first round, with an ace counting as a high card for this purpose. On subsequent rounds, the high handinitiates the action. If the high hand is tied, the first player clockwise from the dealer acts first. Fixed-limit gamesuse the lower limit on third and fourth street and the upper limit on subsequent betting rounds, and an open pairdoes not affect the limit. Aces may be used for high or low. Straights and flushes do not affect the low value of ahand. A player may use any five cards to make the best high hand, and the same or any other grouping of five cardsto make the best low hand.

.Rules of Seven-Card Stud High-Low
. All rules for seven-card stud apply to seven-card stud high-low split, except as otherwise noted.
. A qualifier of 8-or-better for low applies to all high-low split games, unless a specific posting to the contrary isdisplayed. If there is no qualifying hand for low, the best high hand wins the whole pot.
. A player may use any five cards to make the best high hand and any five cards, whether the same as the highhand or not, to make the best low hand.
. The low card by suit initiates the action on the first round, with an ace counting as a high card for this purpose.
. An ace may be used for high or low.
. Straights and flushes do not affect the value of a low hand.
. Fixed-limit games use the lower limit on third and fourth streets and the upper limit on subsequent rounds. Anopen pair on fourth street does not affect the limit.
. Splitting pots is only determined by the cards and not by agreement among players.
. When there is an odd chip in a pot, the chip goes to the high hand. If two players split the pot by tying for boththe high and the low, the pot shall be split as evenly as possible, and the player with the highest card by suit receives the odd chip. When making this determination, all cards are used, not just the five cards used for thefinal hand played.
. When there is one odd chip in the high portion of the pot and two or more high hands split all or half the pot,the odd chip goes to the player with the high card by suit. When two or more low hands split half the pot, theodd chip goes to the player with the low card by suit.

== Lowball

Lowball is draw poker with the lowest hand winning the pot. Each player is dealt five cards facedown, after whichthere is a betting round. Players are required to open with a bet or fold. The players who remain in the pot after thefirst betting round now have an option to improve their hand by replacing cards in their hands with new ones. Thisis the draw. The game is normally played with one or more blinds, sometimes with an ante added. Some bettingstructures allow the big blind to be called; other structures require the minimum open to be double the big blind. Inlimit poker, the usual structure has the limit double after the draw (Northern California is an exception). The mostpopular forms of lowball are ace-to-five lowball (also known as California lowball), and deuce-to-seven lowball(also known as Kansas City lowball). Ace-to-five lowball gets its name because the best hand at that form is 5-4-3-2-A. Deuce-to-seven lowball gets its name because the best hand at that form is 7-5-4-3-2 (not of the same suit).For a further description of the forms of lowball, please see the individual section for each game. All rulesgoverning kill pots are listed in “Section 13 – Kill Pots.”

=== Rules of Lowball
. The rules governing misdeals for hold’em and other button games will be used for lowball. [See “Section 16 –Explanations,” discussion #7, for more information on this rule.] These rules governing misdeals are reprintedhere for convenience.“The following circumstances cause a misdeal, provided attention is called to the error before two players haveacted on their hands:
.. The first or second card of the hand has been dealt faceup or exposed through dealer error.
.. Two or more cards have been exposed by the dealer.
.. Two or more extra cards have been dealt in the starting hands of a game.
.. An incorrect number of cards has been dealt to a player, except the button may receive one more card tocomplete a starting hand.
.. The button was out of position.
.. The first card was dealt to the wrong position.
.. Cards have been dealt out of the proper sequence.
.. Cards have been dealt to an empty seat or a player not entitled to a hand.
.. A player has been dealt out who is entitled to a hand. This player must be present at the table or haveposted a blind or ante.”
. As a new player, you have two options:
.. To wait for the big blind.
.. To kill the pot for double the amount of the big blind.
. In a single-blind game, a player who has less than half a blind may receive a hand. However, the next player isobligated to take the blind. If the all-in player wins the pot or buys in again, that player will then be obligatedto either take the blind on the next deal or sit out until due for the big blind.
. In single-blind games, half a blind or more constitutes a full blind.
. In single-blind games, if you fail to take the blind, you may only be dealt in on the blind.
. In multiple-blind games, if for any reason the big blind passes your seat, you may either wait for the big blindor kill the pot in order to receive a hand. This does not apply if you have taken all of your blinds and changedseats. In this situation, you may be dealt in as soon as your position relative to the blinds entitles you to a hand(the button may go by you once without penalty).
. Before the draw, whether an exposed card must be taken depends on the form of lowball being played; see thatform. (The player never has an option.)
. On the draw, an exposed card cannot be taken. The draw is completed to each player in order, and then theexposed card is replaced.
. A player may draw up to four consecutive cards. If a player wishes to draw five new cards, four are dealt rightaway, and the fifth card after everyone else has drawn cards. If the last player wishes to draw five new cards,four are dealt right away, and a card is burned before the player receives a fifth card. [See “Section 16 –Explanations,” discussion #9, for more information about this rule.]
. Five cards constitute a playing hand; more or fewer than five cards after the draw constitutes a fouled hand.Before the draw, if you have fewer than five cards in your hand, you may receive additional cards, provided noaction has been taken by the first player to act (unless that action occurs before the deal is completed).However, the dealer position may still receive a missing fifth card, even if action has taken place. If action hasbeen taken, you are entitled on the draw to receive the number of cards necessary to complete a five-cardhand.
. You may change the number of cards you wish to draw, provided:
.. No card has been dealt off the deck in response to your request (including the burncard).
.. No player has acted, in either the betting or indicating the number of cards to be drawn, based on thenumber of cards you have requested.
. If you are asked how many cards you drew by another active player, you are obligated to respond until therehas been action after the draw, and the dealer is also obligated to respond. Once there is any action after the draw, you are no longer obliged to respond and the dealer cannot respond.
. Rapping the table in turn constitutes either a pass or the declaration of a pat hand that does not want to drawany cards, depending on the situation.
. Cards speak (cards read for themselves). However, you are not allowed to claim a better hand than you hold.(Example: If a player calls an "8", that player must produce at least an "8" low or better to win. But if a playererroneously calls the second card incorrectly, such as “8-6” when actually holding an 8-7, no penalty applies.)If you miscall your hand and cause another player to foul his or her hand, your hand is dead. If both handsremain intact, the best hand wins. If a miscalled hand occurs in a multihanded pot, the miscalled hand is dead,and the best remaining hand wins the pot. For your own protection, always hold your hand until you see youropponent’s cards.
. Any player spreading a hand with a pair in it must announce "pair" or risk losing the pot if it causes any otherplayer to foul a hand. If two or more hands remain intact, the best hand wins the pot.

=== Ace-to-Five Lowball

In ace-to-five lowball, the best hand is any 5-4-3-2-A. Straights and flushes do not count against your hand.
. If a joker is used, it becomes the lowest card not present in your hand. The joker is assumed to be in use unlessthe contrary is posted.
. In limit play, check-raise is not permitted (unless the players are alerted that it is allowed).
. In limit ace-to-five lowball, before the draw, an exposed card of seven or under must be taken, and an exposedcard higher than a seven must be replaced after the deal has been completed. This first exposed card is used asthe burncard. [See “Section 16 – Explanations,” discussion #8, for more information on this rule.]
. Some lowball games may wish to employ the “sevens rule.” It works as follows. If you check a seven or betterand it is the best hand, all action after the draw is void, and you cannot win any money on any subsequentbets. You are still eligible to win whatever existed in the pot before the draw if you have the best hand. If youcheck a seven or better and the hand is beaten, you lose the pot and any additional calls you make. If there isan all-in bet after the draw that is less than half a bet, a seven or better may just call and win that bet.However, if another player overcalls this short bet and loses, the person who overcalls receives the bet back.If the seven or better completes to a full bet, this fulfills all obligations.

=== Deuce-to-Seven Lowball

In deuce-to-seven lowball (sometimes known as Kansas City lowball), in most respects, the worst conventionalpoker hand wins. Straights and flushes count against you, crippling the value of a hand. The ace is used only as ahigh card. Therefore, the best hand is 7-5-4-3-2, not all of the same suit. The hand 5‑4‑3‑2‑A is not considered tobe a straight, but an ace-5 high, so it beats other ace-high hands and pairs, but loses to king-high.A pair of aces isthe highest pair, so itloses to any other pair. The rules for deuce-to-seven lowball are the same as those for ace-to-five lowball, except for the followingdifferences:
. The best hand is 7-5-4-3-2 of at least two different suits. Straights and flushes count against you, and aces areconsidered high only.
. Before the draw, an exposed card of 7, 5, 4, 3, or, 2 must be taken. Any other exposed card must be replaced(including a 6).
. Check-raise is allowed on any hand after the draw, and a seven or better is not required to bet.

=== No-Limit and Pot-Limit Lowball

. All the rules for no-limit and pot-limit poker (see Section 14 - No-limit and Pot-limit) apply to no-limit andpot-limit lowball. All other lowball rules apply, except as noted.
. A player is not entitled to know that an opponent does not hold the best possible hand, so these rules forexposed cards before the draw apply:
.. In ace-to-five lowball, a player must take an exposed card of A, 2, 3, 4, or 5, and any other card must bereplaced.
.. In deuce-to-seven lowball, the player must take an exposedcard of 2, 3, 4, 5, or 7, and any other cardincluding a 6 must be replaced.
. After the draw, any exposed card must be replaced.
. After the draw, a player may check any hand without penalty (The sevens rule is not used).
. Check-raise is allowed.

== Draw High

There are two betting rounds, one before the draw and one after the draw. The game is played with a button and anante. Players in turn may check, open for the minimum, or open with a raise. After the first betting round theplayers have the opportunity to draw new cards to replace the ones they discard. Action after the draw starts withthe opener, or next player proceeding clockwise if the opener has folded. The betting limit after the draw is twicethe amount of the betting limit before the draw. Some draw high games allow a player to open on anything; othersrequire the opener to have a pair of jacks or better.

=== Rules of Draw High

. A maximum of a bet and four raises is permitted in multihanded pots. [See “Section 16 – Explanations,”discussion #6, for more information on this rule.]
. Check-raise is permitted both before and after the draw.
. Any card that is exposed by the dealer before the draw must be kept.
. Five cards constitute a playing hand. Less than five cards for a player (other than the button) before action hasbeen taken is a misdeal. If action has been taken, a player with fewer than five cards may draw the number ofcards necessary to complete a five-card hand. The button may receive the fifth card even if action has takenplace. More or fewer than five cards after the draw constitutes a fouled hand.
. A player may draw up to four consecutive cards. If a player wishes to draw five new cards, four are dealt rightaway, and the fifth card after everyone else has drawn cards. If the last player wishes to draw five new cards,four are dealt right away, and a card is burned before the player receives a fifth card. [See “Section 16 –Explanations,” discussion #9, for more information about this rule.]
. You may change the number of cards you wish to draw, provided:
.. No cards have been dealt off the deck in response to your request (including the burncard).
.. No player has acted, in either the betting or indicating the number of cards to be drawn, based on thenumber of cards you have requested.
. If you are asked how many cards you drew by another active player, you are obligated to respond until therehas been action after the draw, and the dealer is also obligated to respond. Once there is any action after thedraw, you are no longer obliged to respond and the dealer cannot respond.
. On the draw, an exposed card cannot be taken. The draw is completed to each player in order, and then theexposed card is replaced.
. Rapping the table in turn constitutes either a pass or the declaration of a pat hand that does not want to drawany cards, depending on the situation. A player who indicates a pat hand by rapping the table, not knowing thepot has been raised, may still play his or her hand.
. You may not change your seat between hands when there are multiple antes or forfeited money in the pot.
. You have the right to pay the ante (whether single or multiple) at any time and receive a hand, unless there isany additional money in the pot that has been forfeited during a hand in which you were not involved.
. If the pot has been declared open by an all-in player playing for just the antes, all callers must come in for thefull opening bet.
. If you have only a full ante and no other chips on the table, you may play for just the antes. If no one opensand there is another ante, you may still play for that part of the antes that you have matched, without putting inany more money.

=== Jacks-or-Better

. A pair of jacks or better is required to open the pot. If no player opens the pot, the button moves forward andeach player must ante again, unless the limit of antes has been reached for that particular game. (Most gamesallow three consecutive deals before anteing stops.)
. If the opener should show false openers before the draw, any other active player has the opportunity to declarethe pot opened. However, any player who [HP1]originally passed openers is not eligible to declare the pot open.The false opener has a dead hand and the opening bet stays in the pot. Any other bet placed in the pot by theopener may be withdrawn, provided the action before the draw is not completed. If no other player declaresthe pot open, all bets are returned except the opener’s first bet. The first bet and antes will remain in the pot,and all players who were involved in that hand are entitled to play the next hand after anteing again.
. Any player who has legally declared the pot opened must prove openers in order to win the pot.
. In all cases, the pot will play (even if the opener shows or declares a fouled hand) if there has been a raise, twoor more players call the opening bet, or all action is completed before the draw.
. Even if you are all in for just the ante (or part of the ante), you may declare the pot open if you have openers.If you are all in and falsely declare the pot open, you will lose the ante money and may not continue to play onany subsequent deals until a winner is determined. Even if you buy in again, you must wait until the pot hasbeen legally opened and someone else has won it before you can resume playing.
. Once action has been completed before the draw, the opener may not withdraw any bets, whether or not thehand contains openers.
. An opener may be allowed to retrieve a discarded hand to prove openers, at management’s discretion.
. Any player may request that the opener retain the opening hand and show it after the winner of the pot hasbeen determined.
. You may split openers, but you must declare that you are splitting and place all discards under a chip to beexposed by the dealer after the completion of the hand. If you declare that you are splitting openers, but it isdetermined that  you  could  not  possibly have  had  openers when  your  final  hand  is  compared with  yourdiscards, you will lose the pot.
. You are not splitting openers if you retain openers. If you begin with the ace, joker, king, queen of spades, andthe ten of clubs, you are not splitting if you throw the ten of clubs away. You are breaking a straight to draw toa royal flush, and in doing so, you have retained openers (ace-joker for two aces).
. After the draw, if you call the opener’s bet and cannot beat openers, you will not get your bet back. (You havereceived information about opener’s hand that is not free.)

=== The Joker

. The players will be alerted as to whether the joker is in use.
. The joker may be used only as an ace, or to complete a straight, flush, or straight flush. (Thus it is not acompletely wild card.)
. If the joker is used to make a flush, it will be the highest card of the flush not present in the hand.
. Five aces is the best possible hand (four aces and joker).

== Kill Pots

To kill a pot means to post an overblind that increases the betting limit. A full kill is double the amount of the bigblind, and doubles the betting limits. A half kill is one-and-a-half times the big blind, and increases the bettinglimits by that amount. A kill may be optional in a game, and is often used at lowball when a player wants to bedealt in right away instead of waiting to take the big blind. A kill may be required in a game for any time aspecified event takes place. In high-low split games using a required kill, a player who scoops a pot bigger than aset size must kill the next pot. In other games using a required kill, a player who wins two consecutive pots mustkill the next pot. In this type of kill game, a marker called a “kill button” indicates which player has won the pot,and the winner keeps this marker until the next hand is completed. If the player who has the kill button wins asecond consecutive pot and it qualifies monetarily, that player must kill the next pot.

.Rules of Kill Pots
. The kill button is neutral (belonging to no player) if:
.. It is the first hand of a new game.
.. The winner of the previous pot has quit the game.
.. The previous pot was split and neither player had the kill button.
. In a kill pot, the killer acts in proper turn (after the person on the immediate right).
. There is no pot-size requirement for the first pot or "leg" of a kill. For the second "leg" to qualify for a kill, youmust win at least one full bet for whatever limit you are playing, and it cannot be any part of the blindstructure.
. If a player with one "leg up" splits the next pot, that player still has a "leg up" for the next hand. If the playerwho split the pot was the kill in the previous hand, then that player must also kill the next pot.
. A person who leaves the table with a “leg up” toward a kill still has a “leg up” upon returning to the game.
. A player who is required to post a kill must do so that same hand even if wishing to quit or be dealt out. Aplayer who fails to post a required kill blind will not be allowed to participate in any game until the kill moneyis posted.
. Kill blinds are considered part of the pot. If a player with a required kill wins again, then that player must killit again (for the same amount as the previous hand).
. When a player wins both the high and the low pot (“scoops”) in a split-pot game with a kill provision, the nexthand will be killed only if the pot is at least five times the size of the upper limit of the game.
. If you are unaware that the pot has been killed and put in a lesser amount, If it is a required kill pot with thekill button faceup, you must put in the correct amount. If not, you may withdraw the chips and reconsider youraction.
. In lowball, an optional rule is allowing players to look at their first two cards and then opt whether to kill thepot. The pot may no longer be killed if any player in the game has received a third card. In order to kill the potvoluntarily, you must have at least four times the amount of the kill blind in your stack. For example: If the bigblind is two chips, and the kill blind is four chips, the voluntary killer must have at least 16 chips prior toposting the kill. If this rule is used, it is in conjunction with having the killer act last on the first betting roundrather than in proper order.
. Only one kill is allowed per deal.
. A new player is not entitled to play in a killed pot, but may do so by agreeing to kill the next pot.
. Broken game status is allowed only for players of the same limit and game type. For this purpose, a game witha required kill is considered a different type of game than an otherwise similar game without a required kill.

== No Limit and Pot-Limit

A no-limit or pot-limit betting structure for a game gives it a different character from limit poker, requiring aseparate set of rules in many situations. All the rules for limit games apply to no-limit and pot-limit games, exceptas noted in this section. No-limit means that the amount of a wager is limited only by the table stakes rule, so anypart or all of a player’s chips may be wagered. The rules of no-limit play also apply to pot-limit play, except that abet may not exceed the pot size. For those rules that apply only to no-limit and pot-limit lowball, see the sub-section at the end of “Section 11 – Lowball.”

=== No-Limit Rules

. The number of raises in any betting round is not limited.
. All bets must be at least equal to the minimum bring-in, unless the player is going all-in. (A straddle bet sets anew minimum bring-in, and is not treated as a raise.)
. All raises must be equal to or greater than the size of the previous bet or raise on that betting round, except foran all-in wager. A player who has already checked or called may not subsequently raise an all-in bet that isless than the full size of the last bet or raise. (The half-the-size rule for reopening the betting is for limit pokeronly.)Example: Player A bets $100 and Player B raises $100 more, making the total bet $200. If Player C goes all infor less than $300 total (not a full $100 raise), and Player A calls, then Player B has no option to raise again, because he wasn’t fully raised. (Player A could have raised, because Player B raised.)
. A wager is not binding until the chips are actually released into the pot, unless the player has made a verbalstatement of action.
. If there is a discrepancy between a player's verbal statement and the amount put into the pot, the bet will becorrected to the verbal statement.
. If a call is short due to a counting error, the amount must be corrected, even if the bettor has shown down asuperior hand.
. Because the amount of a wager at big-bet poker has such a wide range, a player who has taken action based ona gross misunderstanding of the amount wagered needs some protection. A bettor should not show down ahand until the amount put into the pot for a call seems reasonably correct, or it is obvious that the callerunderstands the amount wagered. The decision-maker is allowed considerable discretion in ruling on this typeof situation. A possible rule-of-thumb is to disallow any claim of not understanding the amount wagered if thecaller has put eighty percent or more of that amount into the pot.Example: On the end, a player puts a $500 chip into the pot and says softly, “Four hundred.” The opponentputs a $100 chip into the pot and says, “Call.” The bettor immediately shows the hand. The dealer says, “Hebet four hundred.” The caller says, “Oh, I thought he bet a hundred.” In this case, the recommended rulingnormally is that the bettor had an obligation to not show the hand when the amount put into the pot wasobviously short, and the “call” can be retracted. Note that the character of each player can be a factor.(Unfortunately, situations can arise at big-bet poker that are not so clear-cut as this.)
. A player who says "raise" is allowed to continue putting chips into the pot with more than one move; thewager is assumed complete when the player’s hands come to rest outside the pot area. (This rule is usedbecause no-limit play may require a large number of chips be put into the pot.)
. A bet of a single chip or bill without comment is considered to be the full amount of the chip or bill allowed.However, a player acting on a previous bet with a larger denomination chip or bill is calling the previous betunless this player makes a verbal declaration to raise the pot. (This includes acting on the forced bet of the bigblind.)
. If a player tries to bet or raise less than the legal minimum and has more chips, the wager must be increased tothe proper size. (This does not apply to a player who has unintentionally put too much in to call.) The wager isbrought up to the sufficient amount only, no greater size.
. All wagers may be required to be in the same denomination of chip (or larger) used for the minimum bring-in,even if smaller chips are used in the blind structure. If this is done, the smaller chips do not play except inquantity, even when going all-in.
. In non-tournament games, one optional live straddle is allowed. The player who posts the straddle has lastaction for the first round of betting and is allowed to raise. To straddle, a player must be on the immediate left of the big blind, and must post an amount twice the size of the big blind.
. In all no-limit and pot-limit games, the house has the right to place a maximum time limit for taking action onyour hand. The clock may be put on someone by the dealer as directed by a floorperson, if a player requests it.If the clock is put on you when you are facing a bet, you will have one additional minute to act on your hand.You will have a ten-second warning, after which your hand is dead if you have not acted.
. "Insurance" or any other “proposition wagers” are not allowed. Players are asked to refrain from instigatingproposition wagers in any form. The players are allowed to agree to deal twice (or three times) when someoneis all-in. “Dealing twice” means the pot is divided in two, with each portion being dealt for separately.

=== Pot-Limit Rules

. If a wager is made that exceeds the pot size, the surplus will be given back to the bettor as soon as possible,and the amount will be reduced to the maximum allowable.
. The dealer or any player in the game can and should call attention to a wager that appears to exceed the potsize (this also applies to heads-up pots). The oversize wager may be corrected at any point until all playershave acted on it.
. If an oversize wager has stood for a length of time with someone considering what action to take, that personhas had to act on a wager that was thought to be a certain size. If the player then decides to call or raise, andattention is called at this late point to whether this is an allowable amount, the floorperson may rule that theoversize amount must stand (especially if the person now trying to reduce the amount is the person that madethe wager).
. The maximum amount a player can raise is the amount in the pot after the call is made. Therefore, if a pot is$100, and someone makes a $50 bet, the next player can call$50 and raise the pot $200, for a total wager of$250.
. In pot-limit play, it is advisable in many structures to round off the pot size upward to produce a faster pace ofplay. This is done by treating any odd amount as the next larger size. For example, if the pot size was beingkept track of with $25 units, then a pot size of $80 would be treated asa pot size of $100.
. In pot-limit hold’em and pot-limit Omaha, many structures treat the little blind as if it were the same size ofthe big blind in computing pot size. In such a structure, a player can open for a maximum of four times thesize of the big blind. For example, if the blinds are $5 and $10, a player may open with a raise to $40. (Therange of options is to either open with a call of $10, or raise in increments of five dollars to any amount from$20 to $40.) Subsequent players also treat the $5 as if it were $10 in computing the pot size, until the big blindis through acting on the first betting round.
. In pot-limit, if a chip or a bill larger than the pot size is put into the pot without comment, it is considered to bea bet of the pot size.

== Tournaments

By participating in any tournament, you agree to abide by the rules and behave in a courteous manner. A violatormay be verbally warned, suspended from play for a specified length of time, or disqualified from the tournament.Chips from a disqualified participant will be removed from play.

. Whenever possible, all rules are the same as those that apply to live games.
. Initial seating is determined by random draw or assignment. (For a one-table event, cards to determine seatingmay be left faceup so the earlier entrants can pick their seat, since the button is assigned randomly.)
. The appropriate starting amount of chips will be placed on the table for each paid entrant at the beginning ofthe event, whether the person is present or not. Absent players will be dealt in, and all chips necessary forantes and blinds will be put into the pot.
. If a paid entrant is absent at the start of an event, at some point an effort will be made to locate and contact theplayer. If the player requests the chips be left in place until arrival, the request will be honored. If the player isunable to be contacted, the chips may be removed from play at the discretion of the director anytime after anew betting level is begun or a half-hour has elapsed, whichever occurs first.
. A starting stack of chips may be placed in a seat to accommodate late entrants (so all antes and blinds havebeen appropriately paid). An unsold seat will have such a stack removed at a time left to the discretion of thedirector.
. Limits and blinds are raised at regularly scheduled intervals.
. If there is a signal designating the end of a betting level, the new limits apply on the next deal. (A deal beginswith the first riffle of the shuffle.)
. The lowest denomination of chip in play will be removed from the table when it is no longer needed in theblind or ante structure. All lower-denomination chips that are of sufficient quantity for a new chip will bechanged up directly. The method for removal of odd chips is to deal one card to a player for each odd chippossessed. Cards are dealt clockwise starting with the 1-seat, with each player receiving all cards before anycards are dealt to the next player. The player with the highest card by suit gets enough odd chips to exchangefor one new chip, the second-highest card gets to exchange for the next chip, and so forth, until all the lower-denomination chips  are  exchanged. A  player may  not  be  eliminated from  the  event  by  the  chip-changeprocess. If a player has no chips after the race has been held, that player will be given a chip of the higherdenomination before anyone else is awarded a chip. If an odd number of lower-denomination chips are leftafter this process, the player with the highest card remaining will receive a new chip if having half or more ofthe quantity of lower-denomination chips needed, otherwise nothing.
. An absent player is always dealt a hand, and will be put up for blinds, antes, and the forced bet if low.
. A player must be present at the table to stop the action by calling “time.”
. A player must be at the table by the time all players have their complete starting hands in order to have a livehand for that deal. (The dealer has been instructed to kill the hands of all absent players immediately afterdealing each player a starting hand.)
. As players are eliminated, tables are broken in a pre-set order, with players from the broken tables assigned toempty seats at other tables.
. A change of seat is not allowed after play starts, except as assigned by the director.
. In button games, if a player is needed to move from a table to balance tables, the player due for the big blindwill be automatically selected to move, and will be given the earliest seat due for the big blind if more than oneseat is open.
. New players are dealt in immediately and take over the obligations of that position, including the small blind orbutton position.
. The number of players at each table will be kept reasonably balanced by the transfer of a player as needed.With more than six tables, table size will be kept within two players. With six tables or less, table size will bekept within one player.
. In all contests using three or more tables, there is a redraw for seating when the field is reduced to two tables,and again to one table.
. A player who declares all in and loses the pot, then discovers that one or more chips were hidden, is notentitled to benefit from this. That player is eliminated from the tournament if the opponent had sufficient chipsto cover the hidden ones (A rebuy is okay if allowable by the rules of that event). If another deal has not yetstarted, the director may rule the chips belong to the opponent who won that pot, if that obviously would havehappened with the chips out in plain view. If the next deal has started, the discovered chips are removed fromthe tournament.
. If a player lacks sufficient chips for a blind or a forced bet, the player is entitled to get action on whateveramount of money remains. A player who posts a short blind and wins does not need to make up the blind.
. All players must leave their seat immediately after being eliminated from an event.
. Showing cards from a live hand during the action injures the rights of other players still competing in an event,who wish to see contestants eliminated. A player may not show any cards during a deal (unless the event hasonly two remaining players). If a player deliberately shows a card, the player may be penalized (but his handwill not be ruled dead). Verbally stating one’s hand during the play may be penalized.
. The limit on raises is also applied to heads-up situations (except the last two players in a tournament areexempted from a limitation on raises).
. At pot-limit and no-limit play, the player must either use a verbal statement giving the amount of the raise orput the chips into the pot in a single motion. Otherwise, it is a string bet.
. Non-tournament chips are not allowed on the table.
. Higher-denomination chips must be placed where they are easily visible to all other players at the table.
. All tournament chips must remain visible on the table throughout the event. Chips taken off the table orpocketed will be removed from the event, and a player who is caught doing this may be disqualified.
. Inappropriate behavior like throwing cards that go off the table may be punished with a penalty such as beingdealt out for a length of time. A severe infraction such as abusive or disruptive behavior may be punished byeviction from the tournament.
. The deck is not changed on request. Decks change when the dealers change, unless there is a damaged card.
. In all tournament games using a dealer button, the starting position of the button is determined by the playersdrawing for the high card.
. The dealer button remains in position until the appropriate blinds are taken. Players must post all blinds everyround. Because of this, last action may be given to the same player for two consecutive hands by the use of a“dead button.” [See “Section 16 – Explanations,” discussion #1, for more information on this rule.]
. In heads-up play with two blinds, the small blind is on the button.
. At stud, if a downcard on the initial hand is dealt faceup, a misdeal is called.
. If a player announces the intent to rebuy before cards are dealt, that player is playing behind and is obligated tomake the rebuy.
. All hands will be turned faceup whenever a player is all-in and betting action is complete.
. If two (or more) players go broke during the same hand, the player starting the hand with the larger amount ofmoney finishes in the higher tournament place for prize money and any other award.
. Management is not required to rule on any private deals, side bets, or redistribution of the prize pool amongfinalists.
. Private agreements by remaining players in an event regarding distribution of the prize pool are not condoned.(However, if such an agreement is made, the director has the option of ensuring that it is carried out by payingthose  amounts.) Any  private agreement that  excludes one  or  more  active competitors is  improper bydefinition.
. A tournament event is expected to be played until completion. A private agreement that removes all prizemoney from being at stake in the competition is unethical.
. Management retains the right to cancel any event, or alter it in a manner fair to the players.

== Explanations

. The only place in this set of rules that an alternative is mentioned other than in this section is in the method of button and blind placement.
	That rule (the first rule in <<Button and Blind Use>>) is repeated below for convenience.
+
[quote]
Each round all participating players must get an opportunity for the button, and meet the total amount of theblind obligations.
Either of the following methods of button and blind placement may be designated to do this: +
(a) Moving button – The button always moves forward to the next player and the blinds adjust accordingly.
There may be more than one big blind. +
(b) Dead button – The big blind is posted by the player due for it, and the small blind and button are positionedaccordingly, even if this means the small blind or the button is placed in front of an empty seat, giving thesame player the privilege of last action on consecutive hands.
+
Poker tradition has a lot to do with the fact that both of these methods are in widespread use, but neither method is superior in all situations.
The moving button makes sure no player gets the advantage of last actiontwice on a round (a big advantage at no-limit or pot-limit play).
On the other hand, a player may get to post ablind when on the button, which is more advantageous than posting in front of the button.
The moving buttoncreates a situation where two big blinds may be posted on a deal, which speeds up the action.
At tournament play this speed-up can be undesirable, as when dealing is being done hand-for-hand to balance the pace of playbetween two remaining tables.
A cardroom may either decide for the sake of simplicity to use only one method,or decide to tailor the method to the game and situation.
. The rules given for rectifying a hold’em situation where the dealer has dealtthe flop or another boardcardbefore all the betting action on a round are inferior, because the dealer is told to not burn a card on a redeal.
	Since the “no burn” rule is so common, there was no choice but to use it here.
	But at some point it would begood  for  poker  for  some  major  cardrooms  to  get  together and  agree  to  use  the  better  rule,  or  a  gamingcommission to require the better rule be used.
	Here is the rules in question (the third rule and fourth rule in <<holdem>>).
+
[quote]
If the cards are prematurely flopped before the betting is complete, or if the flop contains too many cards, theboardcards are mixed with the remainder of the deck.
The burncard remains on the table.
After shuffling, thedealer cuts the deck and deals a new flop without burning a card.
+
[quote]
If the dealer turns the fourth card on the board before the betting round is complete, the card is taken out ofplay for that round, even if subsequent players elect to fold.
The betting is then completed.
The dealer burnsand turns what would have been the fifth card in the fourth card’s place.
After this round of betting, the dealerreshuffles the deck, including the card that was taken out of play, but not including the burncards or discards.
The dealer then cuts the deck and turns the final card without burning a card. (If the fifth card is turned upprematurely, the deck is reshuffled and dealt in the same manner.)
+
The portion of this rule saying the dealer does not burn a card on the redeal is misguided. It is much harder forthe dealer to control the card to be dealt if a burn is required. The applicable sentence in the rule should read,“The dealer then cuts the deck, burns a card, and turns the final card.”
. Rule seven in <<Button and Blind Use>> says,
+
[quote]
A new player cannot be dealt in between the bigblind and the button.
Blinds may not be made up between the big blind and the button. You must wait until thebutton passes.
+
This rule is standard practice, but allowing a new player or player making up blinds to come inbetween the blinds is better (if the dealer knows how to handle the resulting situations), because it gets players eager to join or rejoin the game into action faster.
. Most poker rule sets say you have a dead hand at the showdown if you do not have the proper number of cardsfor that game.
At stud, this rule is too strict.
An inexperienced player sometimes does not pay sufficientattention to the final card when holding a big hand like a flush or full house (where improvement is neitherlikely to happen nor be needed), and fails to protect that card.
If the dealer erroneously puts that final card intothe muck after the player fails to take it in, the rules should give the decision-maker an option to rule such ahand live.
Rule 18 in <<Seven-Card Stud>> reads as below:
+
[quote]
A hand with more than seven cards is dead.
A hand with less than seven cards at the showdown is dead,except any player missing a seventh card may have the hand ruled live.
. This rulebook requires all cash to be changed into chips.
	In some games this can be a bit impractical for various reasons.
	If the game chooses to allow cash, only large bills should be permitted.
. Most poker rulebooks follow the usual California practice in multihanded pots at limit poker of allowing a betand six raises for lowball and draw high.
	The number of allowable raises for those games is given in thisrulebook as a bet and three raises because this cuts down on the effect of collusion between players, and moreraises than three are seldom needed to define the strength of two hands when another player is calling.
. Lowball has historically had less stringent demands on the order of cards or acceptability of exposed cards thanin most other poker forms.
	This rulebook follows the modern trend at lowball regarding misdeals of requiringthe cards to be dealt facedown and in proper order.
. At ace-to-five limit lowball, an exposed card rule used less often, but probably a superior rule, is to not let aplayer take an exposed six or seven (the rule for no-limit ace-to-five lowball).
	If a player gets to keep only acard that might make a perfect hand, having a card exposed is less advantageous, and the opponent must reckonwith the possibility of a perfect hand.
. At lowball and draw high, some rule sets allow a player to draw five consecutive cards.
	The rule used here disallowing this makes cheating more difficult.
	Our rule #10 in <<Lowball>> and rule #5 in <<Draw High>> says,
+
[quote]
A player may draw up to four consecutive cards.
If a player wishes to draw five new cards, four are dealt rightaway, and the fifth card after everyone else has drawn cards.
If the last player wishes to draw five new cards,four are dealt right away, and a card is burned before the player receives a fifth card.
. In tournament play, there are two ways the hand of an absent player may be treated.
	Our rule #11 in <<Tournaments>> is:
+
[quote]
If you are not present when it becomes your turn to act, your hand is dead.
This includes situations in which a live blind is not present to act, since an absent player cannot exercise the optionto raise.
+
This speeds up play, and also prevents a player from facing situations like thinking he is moving all-in heads-up against a short stack and an absent player comes back to the table to enter the pot.
The alternative is:
+
[quote]
If a player is absent, the hand shall not be killed until that seat faces a wager.
An absent player’s hand isdead at the showdown.
+
This rule gives the absent player the maximum amount of time to return and be ableto play the hand.

[appendix]
== Glossary

ACTION:: A fold, check, call, bet, or raise.
For certain situations, doing something formally connected with thegame that conveys information about your hand may also be considered as having taken action.
Examples wouldbe showing your cards at the end of the hand, or indicating the number of cards you are taking at draw.
